package exceptions_article_first_part;

public class App2 {
    public static void main(String[] args) {
        try {
        } catch (Throwable t) {}
    }
}
